return {
	cmd = {
		"clangd",
		"--background-index",
		"--clang-tidy",
		"--header-insertion=iwyu",
		"--completion-style=detailed",
		"--function-arg-placeholders",
		"--fallback-style=llvm",
		"--log=verbose",
	},
	init_options = {
		fallbackFlags = { "-std=c++23" },
	},
	root_markers = {
		"compile_commands.json",
		"compile_flags.txt",
		"configure.ac",
		"Makefile",
		"configure.ac",
		"configure.in",
		"config.h.in",
		"meson.build",
		"meson_options.txt",
		"build.ninja",
		".git",
		".clangd",
		".clang-tidy",
		".clang-format",
	},
}
